### ISSUE TITLE
Feature request: add support for `OutputStyle` (needs `sass` upgrade)

### ISSUE THREAD

**Issue by CedX** [dart-league/sass_builder#23]
I'm using the `sass_builder` transformer with an Angular application.

`sass` package **v1.0.0-beta.5.1** added support for different output styles, notably the `compressed` output style. It would be cool if I could do this in my `pubspec.yaml` file:

```yaml
transformers:
- sass_builder:
    output_style: compressed
```

...and see my resulting stylesheet minified :)
