### ISSUE TITLE
Malformed type: "cannot resolve class 'Logger' from 'SassBuilder'"

### ISSUE THREAD

**Issue by 4cm4k1** [dart-league/sass_builder#30]
I reported this issue (https://github.com/dart-lang/build/issues/1181) over in [build](https://github.com/dart-lang/build), but maybe it's a change in the latest Dart SDK that `sass_builder` needs to account for?

**Dart:** 2.0.0-dev.39.0
**OS:** macOS 10.13.4 beta (17E182a)
**Browser:** N/A

**`pubspec.yaml`:**
```yaml
dependencies:
  angular: ^5.0.0-alpha+8
  angular_components: ^0.9.0-alpha+7
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha+8
  firebase: ^4.4.0
  pwa: ^0.1.9+1

dev_dependencies:
  angular_ast: ^0.4.4
  angular_compiler: ^0.4.0-alpha+8
  angular_test: ^2.0.0-alpha+6
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+1
  sass_builder: ^1.1.4
  test: ^0.12.32+1

dependency_overrides:
  angular: ^5.0.0-alpha+8
  angular_forms: ^2.0.0-alpha
```

**Error output:**
```shell
[INFO] Generating build script completed, took 377ms

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

'package:sass_builder/sass_builder.dart': malformed type: line 34 pos 20: cannot resolve class 'Logger' from 'SassBuilder'
  final _log = new Logger('sass_builder');
                   ^

dart:core                                                          _TypeError._throwNew
package:sass_builder/sass_builder.dart 34:20                       new SassBuilder
package:angular_components/builder.dart 9:9                        scssBuilder
package:build_runner/src/package_graph/apply_builders.dart 150:37  new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner/src/package_graph/apply_builders.dart 261:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                          List.addAll
package:build_runner/src/package_graph/apply_builders.dart 215:7   createBuildPhases
package:build_runner/src/generate/build_impl.dart 93:13            build
package:build_runner/src/generate/build.dart 66:5                  build
package:build_runner/src/entrypoint/options.dart 266:24            _BuildCommand.run
package:args/command_runner.dart 194:27                            CommandRunner.runCommand
package:args/command_runner.dart 109:29                            CommandRunner.run.<fn>
dart:async                                                         new Future.sync
package:args/command_runner.dart 109:11                            CommandRunner.run
package:build_runner/src/entrypoint/run.dart 15:24                 run
.dart_tool/build/entrypoint/build.dart 49:22                       main
```

**Comment by alfinbi** [comment]
same problem with me here since using dart 2.0.0-dev.38.0 and the problem also occurs in dart 2.0.0-dev.39.0. I have tried using dart 1.24.3, the problem is still there.

update : I notice this problem occurs in windows, after switch to linux, there is no problem at all using any dart version

**Comment by muzuro** [comment]
Same issue in docker image `google/dart`, have tried `latest`, `1.25.0-dev.11.0`, `1.24`. Build is executed in gitlab pipeline job. Here is [stackoverflow question](https://stackoverflow.com/questions/49334361/dart-sassbuilder-cannot-find-logger) about same issue.

**Comment by ltackmann** [comment]
Same issue in here with docker image google/dar and dart 1.25.0-dev.11.0, 1.24.

**Comment by CedX** [comment]
Same issue with Dart 2.0.0-dev.39 on Ubuntu 17.10 and this `pubspec.yaml`:

```yaml
dependencies:
  angular: ^4.0.0
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  github: ^3.0.2
  http: ^0.11.3
  ngx_core: ^0.6.0
  usage: ^3.3.0

dev_dependencies:
  grinder: ^0.8.1
  package_resolver: ^1.0.2
  sass: ^1.0.0-rc.1
  sass_builder: ^1.1.4
  yaml: ^2.1.13

transformers:
- sass_builder
- angular:
    entry_points: web/js/main.dart
- $dart2js:
    commandLineOptions: [--use-old-frontend]
```

Editing the `SassBuilder` class in the pub cache as suggested by [the StackOverflow answer](https://stackoverflow.com/questions/49334361/dart-sassbuilder-cannot-find-logger#answer-49336090) fixed the issue.

**Comment by matanlurey** [comment]
@4cm4k1 @alfinbi @muzuro @ltackmann @cedx 

Are you all using `build_runner v0.8.0`?

**Comment by 4cm4k1** [comment]
@matanlurey yes. 🙂

**Comment by muzuro** [comment]
I don't have line with `build_runner`
Here is my pubspec.yaml:
```
name: app
description: web app
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0+2
  angular_components: ^0.8.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  http: "^0.11.3+16"

dev_dependencies:
  angular_test: ^1.0.1
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  sass_builder: ^1.1.4

transformers:
- sass_builder
- angular:
    entry_points:
      - public/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    sourceMaps: true
- dart_to_js_script_rewriter
```
Here is error stack:
```
Loading angular, sass_builder, test/pub_serve and dart_to_js_script_rewriter transformers...
Error on line 26, column 5 of /root/.pub-cache/hosted/pub.dartlang.org/angular_components-0.8.0/pubspec.yaml: Error loading transformer: 'package:sass_builder/sass_builder.dart': malformed type: line 34 pos 20: cannot resolve class 'Logger' from 'SassBuilder'
  final _log = new Logger('sass_builder');
                   ^


    outputExtension: .scss.css
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error on line 25, column 3 of pubspec.yaml: Error loading transformer: 'package:sass_builder/sass_builder.dart': malformed type: line 34 pos 20: cannot resolve class 'Logger' from 'SassBuilder'
  final _log = new Logger('sass_builder');
                   ^


- sass_builder
  ^^^^^^^^^^^^
```
