### ISSUE TITLE
Import from package not working

### ISSUE THREAD

**Issue by sandrija** [dart-league/sass_builder#45]
Hi,
I have issues with import:
for example: 
@import "package:bootstrap_sass/scss/variables"; is not working in my project.
Error. cannot resolve directory...
And then in browser main.css get rejected due that error: 

However: 
@import "sub"; works fine.

pubspec.yaml:

```
environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  angular_router: ^2.0.0-alpha+15
  bootstrap_sass: 4.1.0
  firebase: ^4.5.1
  path: 1.6.1
  sass: ^1.5.0

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  sass_builder: 2.1.1
  service_worker: ^0.2.0
  test: ^1.0.0
```
