### ISSUE TITLE
sass_builder doesn't build CSS files

### ISSUE THREAD

**Issue by sestegra** [dart-league/sass_builder#46]
When executing `webdev serve`, CSS files are created in `.dart_tool` directory.

But, when execution `webdev build`, no CSS files are present in `build` directory.

See my pubspec.yaml content.
``` yml
environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta+1
  angular_components: ^0.9.0-beta
  angular_forms: ^2.0.0-beta+1
  angular_router: ^2.0.0-alpha+16

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.1
  build_test: ^0.10.3
  build_web_compilers: ^0.4.0+4
  grinder: ^0.8.0+2
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.0-alpha
  sass: ^1.9.0
  sass_builder: ^2.1.0
```

**Comment by sestegra** [comment]
See verbose logs of `webdev build`
```
[INFO] Build:Running build...
[FINE] sass_builder on lib/styles/form.scss:compiling file: package:web_app/styles/form.scss
[FINE] sass_builder on lib/styles/form.scss:wrote css file: lib/styles/form.css
```

`lib/styles/form.css` is found in `.dart_tool` directory, but not in `build`.

**Comment by sestegra** [comment]
See following a workaround
``` bash
#!/bin/bash

NAME=$(grep 'name:' pubspec.yaml|cut -d':' -f2|xargs)

ROOT=$(pwd)
SERVE=$ROOT/.dart_tool/build/generated/$NAME/lib
BUILD=$ROOT/build/packages/$NAME

cd $SERVE
for FILE in $(find . -name *.css); do
  mkdir -p $BUILD/$(dirname $FILE)
  cp -v $FILE $BUILD/$FILE
done
```

**Comment by nshahan** [comment]
As I understand this is working as intended because the angular package is cleaning up these .css input sources after they are turned into generated Dart code.

The most accepted approach would be to disable the post-process builder that angular uses to cleanup and then build to an output directory.

In your build.yaml:
```yaml
global_options:
  angular|component_source_cleanup:
    release_options:
      enabled: false
```

At the command line: `$ webdev build -o output_dir_name`

**Comment by enyo** [comment]
Thanks @nshahan for the explanation. In my case I have a few CSS files that are completely unrelated to angular and I'd like them to be included in the build directory, but I would like to avoid keeping all the `.css` files for components. Is the disabling of the post-process builder the only option I have?

**Comment by nshahan** [comment]
You could also specify a build.yaml file for your package and configure specific file excludes for the builder in the angular package that performs the cleanup. Something like:
```
targets:
  $default:
    builders:
      angular|component_source_cleanup:
        enabled: true
        generate_for:
          exclude: 
            - "lib/my_non_angular_styles.css"
```
A cleaner solution would be to allow packages to define a cleanup builder that only omits from the output the files that the certain builders consumed instead of all files of that type.

I know there has been discussion about this issue but AFAIK at this time there is no way to define a builder with this type of knowledge. If you feel this would a useful addition, please file an issue on the build repo so we can track the need for it.
https://github.com/dart-lang/build/issues/new
