### ISSUE TITLE
Errors parsing CSS

### ISSUE THREAD

**Issue by insinfo** [dart-league/sass_builder#70]
@simolus3

how do i exclude certain folders and files from being analyzed by sass_buider

#### build.yaml

```
targets:
  $default:
     
    #sources:
      #exclude:
        #- "web/assets/css/**"
        #- "web/styles.css"

    #  sass_builder
    builders:
      sass_builder:
        generate_for:
          - "lib/**"       # not work 
        options:
          outputStyle: compressed
```

```console
ngdart on web/styles.css: Errors parsing CSS:
error on line 29, column 12: parsing error expected {
   ╷
29 │  @supports selector(::-webkit-scrollbar) {
   │            ^^^^^^^^
   ╵
error on line 29, column 20: expected }, but found (
   ╷
29 │  @supports selector(::-webkit-scrollbar) {
   │                    ^
   ╵
error on line 29, column 40: expected {, but found )
   ╷
29 │  @supports selector(::-webkit-scrollbar) {
   │                                        ^
   ╵
error on line 29, column 42: expected }, but found {
   ╷
29 │  @supports selector(::-webkit-scrollbar) {
   │                                          ^
   ╵
error on line 42, column 2: premature end of file unknown CSS
   ╷
42 │  }
   │  ^
   ╵
[SEVERE] ngdart on web/styles.css: Null check operator used on a null value
``` 
#### web/styles.css
```css
 /* no phosphor 1 é \f31a  .ph-caret-down:before
  no phosphor 2.0.3 é \e9fe .ph-caret-down:before*/
 .dropdown-toggle::after {
     display: inline-block;
     margin-left: .25em;
     vertical-align: -.125em;
     font-family: var(--icon-font-family);
     font-size: 1em;
     line-height: 1;
     content: "\e9fe";
 }

 html {
     --scrollbar-color-thumb: rgb(98, 98, 98);
     --scrollbar-color-track: rgb(31, 31, 33);
     --scrollbar-width: thin;
     --scrollbar-width-legacy: 10px;
 }

 /* Modern browsers with `scrollbar-*` support */
 @supports (scrollbar-width: auto) {
     html {
         scrollbar-color: var(--scrollbar-color-thumb) var(--scrollbar-color-track);
         scrollbar-width: var(--scrollbar-width);
     }
 }

 /* Legacy browsers with `::-webkit-scrollbar-*` support */
 @supports selector(::-webkit-scrollbar) {
     html::-webkit-scrollbar-thumb {
         background: var(--scrollbar-color-thumb);
     }

     html::-webkit-scrollbar-track {
         background: var(--scrollbar-color-track);
     }

     html::-webkit-scrollbar {
         max-width: var(--scrollbar-width-legacy);
         max-height: var(--scrollbar-width-legacy);
     }
 }
```

pubspec.yaml

```yaml
name: esic_frontend_site
description: Frontend (WEB) do Sistema Eletrônico de Informações ao. Cidadão (e-SIC)
version: 2.0.0
publish_to: none

environment:
  sdk: ^3.2.1

dependencies:
  ngdart: 8.0.0-dev.4
  ngrouter: 4.0.0-dev.3
  ngforms: 5.0.0-dev.3 

  intl: any
  chartjs2: ^2.0.0
  http: any
  js: any
  pdf: ^3.10.8

  esic_core:
    path: ../core
  #bootstrap_sass: any

dev_dependencies:  
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
  sass_builder: ^2.2.1
```

**Comment by simolus3** [comment]
Applying `generate_for: ['lib/**']` should stop the sass builder from running on `web/` files. You said it doesn't work, what exactly is going wrong?

**Comment by insinfo** [comment]
After some time trying to solve this, I finally got it to work correctly like this:


```yaml
targets:
  $default:  
    builders:
      ngdart:       
        generate_for:
          exclude: 
            - "web/assets/css/**"
            - "web/assets/js/**"
      sass_builder:       
        options:
          outputStyle: compressed
```

It would be nice if this was documented in the sass_builder README.md
